name: sig-tsc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy<=2.2
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - rich
  - joblib
  - pytest
  - jupyterlab

  - pip:
      - aeon